version: "3"
services:
  task2server:
    image: ghcr.io/ameyak04/task2server-ghcr:latest
    ports:
      - '80:80'

  postgresdb:
    image: ghcr.io/ameyak04/postgresdb-ghcr:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
#
