#!/bin/bash

echo "##################Script to request till Return Date###############"

echo -e "My Return Date after Signout is (in YYYYMMDD format Example 20230518) : \n"

read ReturnDate
echo $ReturnDate

RollNumber=$(sed -n '/^RollNumber/p' $HOME/userDetails.txt | awk -F: '{print $2}' )
echo -e "$RollNumber  $ReturnDate" > ../../Return.txt
